---
# The most valuable linters; they are required to pass for PR to be merged.

linters-settings:
  goimports:
    local-prefixes: github.com/percona/promconfig

linters:
  disable-all: true
  enable:
    - depguard
    - exhaustive
    - goimports
    - govet
    - ineffassign
    - staticcheck

issues:
  exclude-use-default: false
