version: "2"
linters:
  default: all
  disable:
    - err113
    - mnd
    - modernize
    - nlreturn
    - tagalign
    - varnamelen
    - wrapcheck
    - wsl
    - wsl_v5
  settings:
    depguard:
      rules:
        main:
          deny:
            - pkg: github.com/pkg/errors
              desc: use "errors" instead
            - pkg: gopkg.in/yaml.v3
              desc: use "gopkg.in/yaml.v2" instead
    tagliatelle:
      case:
        rules:
          yaml: snake
    unparam:
      check-exported: true
  exclusions:
    generated: lax
    rules:
      - path: '(.+)_test\.go'
        linters:
          - cyclop    
          - exhaustruct
          - forcetypeassert
          - godot
          - funlen
          - paralleltest
          - testpackage
          - unused
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - gofumpt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/percona/promconfig
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
