---
name: CI
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  gen:
    name: Generate

    strategy:
      matrix:
        go-version: [1.13.x, 1.14.x]
        platform: [ubuntu-latest]

    runs-on: ${{ matrix.platform }}

    env:
      GOFLAGS: -v -mod=readonly

    steps:
      - name: Set up Go ${{ matrix.go-version }}
        uses: percona-platform/setup-go@v1
        with:
          go-version: ${{ matrix.go-version }}

      - name: Check out code into the Go module directory
        uses: percona-platform/checkout@v2
        with:
          lfs: true

      # useful debug commands
      # - run: env
      # - run: go env
      # - run: pwd

      - name: Enable Go modules cache
        uses: percona-platform/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ matrix.platform }}-go-${{ matrix.go-version }}-modules-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ matrix.platform }}-go-${{ matrix.go-version }}-modules-

      - name: Enable Go build cache
        uses: percona-platform/cache@v1
        with:
          path: ~/.cache/go-build
          key: ${{ matrix.platform }}-go-${{ matrix.go-version }}-build-${{ github.ref }}-${{ hashFiles('**') }}
          restore-keys: |
            ${{ matrix.platform }}-go-${{ matrix.go-version }}-build-${{ github.ref }}-
            ${{ matrix.platform }}-go-${{ matrix.go-version }}-build-

      - name: Download Go modules
        run: go mod download

      - name: Run CI target
        run: make ci
