---
name: Clean
on:
  schedule:
    # run every Saturday
    - cron: "0 12 * * 6"

jobs:
  clean-caches:
    name: Clean caches
    timeout-minutes: 10

    strategy:
      fail-fast: false
      matrix:
        go-version: [ 1.16.x ]
        may-fail: [ false ]
        include:
          - go-version: tip
            may-fail: true

    continue-on-error: ${{ matrix.may-fail }}
    runs-on: ubuntu-20.04

    env:
      GOFLAGS: -mod=readonly

    steps:
      - name: Set up Go release
        if: matrix.go-version != 'tip'
        uses: percona-platform/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Set up Go tip
        if: matrix.go-version == 'tip'
        run: |
          git clone --depth=1 https://go.googlesource.com/go $HOME/gotip
          cd $HOME/gotip/src
          ./make.bash
          echo "GOROOT=$HOME/gotip" >> $GITHUB_ENV
          echo "$HOME/gotip/bin" >> $GITHUB_PATH

      - name: Check out code into the Go module directory
        uses: percona-platform/checkout@v2
        with:
          lfs: true
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Enable Go modules cache
        uses: percona-platform/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ matrix.os }}-go-${{ matrix.go-version }}-modules-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ matrix.os }}-go-${{ matrix.go-version }}-modules-

      - name: Enable Go build cache
        uses: percona-platform/cache@v2
        with:
          path: ~/.cache/go-build
          key: ${{ matrix.os }}-go-${{ matrix.go-version }}-build-${{ github.ref }}-${{ hashFiles('**') }}
          restore-keys: |
            ${{ matrix.os }}-go-${{ matrix.go-version }}-build-${{ github.ref }}-
            ${{ matrix.os }}-go-${{ matrix.go-version }}-build-

      - name: Clean Go modules cache
        run: go clean -modcache

      - name: Clean Go build cache
        run: go clean -cache
